name: ALLINShop
version: '1.0.2'
main: ru.allin.allinshop.ALLINShopPlugin
api-version: '26.2'
authors: [ALLIN]
depend: [Vault]
commands:
  ashop:
    description: ALLINShop admin command
    aliases: [allinshop]
permissions:
  allinshop.use:
    default: true
  allinshop.admin:
    default: op
